### ISSUE TITLE
ADN posting material on social media

### ISSUE THREAD

**Issue by andreadekovic** [singularitynet-latam-ambassador/outreach#4]

**Comment by bluenotgreen** [comment]
## Materials Available:

- Blog post
- LinkedIn Post
- Videos / Picture -> Drive

Video content:
- 5 Questions -> 
- Video with ambassadors about the event experience 

## Suggestions:
-> Shorts: Youtube/TikTok/Instagram -> 

## Visuals
- How will the output look?

Blog post: https://medium.com/p/e4bc960bfdfd/edit

This is the DOC for the AGI RoundTable: https://docs.google.com/document/d/1VB2ovPf7hMgfhXxrZsChZ3iTj5lN6rKztCWsUGlL1ng/edit
